services:
  - type: web
    name: fake-news-detector
    env: python
    buildCommand: |
      # Ensure Git LFS is available and pull LFS files
      git lfs install &&
      git lfs pull &&
      # Run our build script
      chmod +x build.sh &&
      ./build.sh
    startCommand: gunicorn web_app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --preload
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: NLTK_DATA
        value: /opt/render/project/src/nltk_data
      - key: FLASK_ENV
        value: production
    disk:
      name: fake-news-models
      mountPath: /opt/render/project/src/models
      sizeGB: 1
